**Задание**

Обучите нейронную сеть решать шифр Цезаря.

Что необходимо сделать:
Написать алгоритм шифра Цезаря для генерации выборки (сдвиг на К каждой буквы. 

Например, при сдвиге на 2 буква “А” переходит в букву “В” и тп)
- Сделать нейронную сеть
- Обучить ее (вход - зашифрованная фраза, выход - дешифрованная фраза)
- Проверить качество


In [ ]:
import pandas as pd
import time
import torch
import random

##Читаем файл

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ds/onegin.txt', sep='\n\r')#mode='r', newline='')

df.head(20)

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


Евгений Онегин
0                          Александр Сергеевич Пушкин
1                             Классика для школьников
2   Роман в стихах А. С. Пушкина «Евгений Онегин» ...
3                          Александр Сергеевич Пушкин
4                                      Евгений Онегин
5   Pеtri de vanitе il avait encore plus de cette ...
6   Tirе d’une lettre particuli?re[1 - Проникнутый...
7                      He мысля гордый свет забавить,
8                            Вниманье дружбы возлюбя,
9                         Хотел бы я тебе представить
10                              Залог достойнее тебя,
11                         Достойнее души прекрасной,
12                          Святой исполненной мечты,
13                              Поэзии живой и ясной,
14                            Высоких дум и простоты;
15                 Но так и быть – рукой пристрастной
16                       Прими собранье пёстрых глав,
17                        Полусмешных, полупечальных,
18                         Простонародных, идеальных,
19                         Небрежный плод моих забав,

In [ ]:
phrases = df['Евгений Онегин'].tolist()
phrases[:10]

['Александр Сергеевич Пушкин',
 'Классика для школьников',
 'Роман в стихах А.\xa0С.\xa0Пушкина «Евгений Онегин» (1823–1831)\xa0– одно из самых значительных произведений русской литературы. Роман охватывает события с 1819 по 1825 год: от заграничных походов русской армии после разгрома Наполеона до восстания декабристов. По словам известного критика В.\xa0Г.\xa0Белинского, роман – «энциклопедия русской жизни» начала XIX века.',
 'Александр Сергеевич Пушкин',
 'Евгений Онегин',
 'Pеtri de vanitе il avait encore plus de cette esp? ce d’orgueil qui fait avouer avec la m?me indiffеrence les bonnes comme les mauvaises actions, suite d’un sentiment de supеrioritе, peut-?tre imaginaire.',
 'Tirе d’une lettre particuli?re[1 - Проникнутый тщеславием, он обладал сверх того ещё особенной гордостью, которая побуждает признаваться с одинаковым равнодушием как в своих добрых, так и дурных поступках,\xa0– вследствие чувства превосходства, быть может, мнимого.Из частного письма (франц.)]',
 'He мысля 

##Шифруем данные

In [ ]:
small_symbols = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя"
big_symbols = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"


def shift(text, symbols, n):
    index = symbols.find(text)
    if index + n < len(symbols):
        return symbols[index + n]
    else:
        return symbols[(index + n) % len(symbols)]

    

def back_shift(text, symbols, n):
    index = symbols.find(text)
    if index - n >= 0:
        return symbols[index - n]
    else:        
        return symbols[(index - n) % len(symbols)]

    

def encrypt(text, n):
    res = ""

    for i in range(0, len(text)): 
        if text[i].isupper():
            res += shift(text[i], big_symbols, n)
        
        elif text[i].islower():
            res += shift(text[i], small_symbols, n)
        else:
            res += text[i]
        
    return res


def decrypt (text, n):
    res = ""
                   
    for i in range(0, len(text)):
        if text[i].isupper():
            res += back_shift(text[i], big_symbols, n)
        
        elif text[i].islower():
            res += back_shift(text[i], small_symbols, n)
        else:
            res += text[i]
        
    return res


In [ ]:
len(small_symbols)

33

In [ ]:
encrypt_phrases = []
#n = input('введите сдвиг: ')
for i in range(len(phrases)):
  str = phrases[i]
  #str_enc = encrypt(str, int(n))
  str_enc = encrypt(str, random.randint(1, len(small_symbols)-1))
  encrypt_phrases.append(str_enc)

print('оригинальный текст:  ', phrases[:3])
print('зашифрованный текст: ', encrypt_phrases[:3])



оригинальный текст:   ['Александр Сергеевич Пушкин', 'Классика для школьников', 'Роман в стихах А.\xa0С.\xa0Пушкина «Евгений Онегин» (1823–1831)\xa0– одно из самых значительных произведений русской литературы. Роман охватывает события с 1819 по 1825 год: от заграничных походов русской армии после разгрома Наполеона до восстания декабристов. По словам известного критика В.\xa0Г.\xa0Белинского, роман – «энциклопедия русской жизни» начала XIX века.']
зашифрованный текст:  ['Ьзбжньйам Нбмяббюеу Лпфжей', 'Яафёёэяф шау мягарвэягц', 'Цфтёу з чшоыёы Ё.\xa0Ч.\xa0Хщюроуё «Кзикуоп Фукиоу» (1823–1831)\xa0– фйуф он чётбы нуёэошксвубы хцфонзкйкуоп цщччрфп сошкцёшщцб. Цфтёу фызёшбзёкш чфжбшое ч 1819 хф 1825 ифй: фш нёицёуоэубы хфыфйфз цщччрфп ёцтоо хфчск цёницфтё Уёхфскфуё йф зфччшёуое йкрёжцочшфз. Хф чсфзёт онзкчшуфиф рцошорё З.\xa0И.\xa0Жксоучрфиф, цфтёу – «гуьорсфхкйое цщччрфп монуо» уёэёсё ЕЕЕ зкрё.']


##Делаем массив с данными

In [ ]:
CHARS = set('АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя ')
INDEX_TO_CHAR = ['none'] + [w for w in CHARS]
CHAR_TO_INDEX = {w: i for i, w in enumerate(INDEX_TO_CHAR)}

In [ ]:
len(INDEX_TO_CHAR)

68

In [ ]:
MAX_LEN = 68
y = torch.zeros((len(phrases), MAX_LEN), dtype=int)
for i in range(len(phrases)):
    for j, w in enumerate(phrases[i]):
        if j >= MAX_LEN:
            break
        y[i, j] = CHAR_TO_INDEX.get(w, CHAR_TO_INDEX['none'])

In [ ]:
print(CHAR_TO_INDEX['А'],CHAR_TO_INDEX['л'],CHAR_TO_INDEX['е'], CHAR_TO_INDEX['к'], CHAR_TO_INDEX['с'])
y[0:3]

51 20 38 41 48


tensor([[51, 20, 38, 41, 48, 52, 35, 47, 32, 24,  3, 38, 32, 62, 38, 38, 53, 16,
          1, 24, 50,  8,  4, 41, 16, 35,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [18, 20, 52, 48, 48, 16, 41, 52, 24, 47, 20, 17, 24,  4, 41, 42, 20, 43,
         35, 16, 41, 42, 53,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 42, 60, 52, 35, 24, 53, 24, 48, 63, 16, 12, 52, 12, 24, 51,  0,  0,
          3,  0,  0, 50,  8,  4, 41, 16, 35, 52, 24,  0, 67, 53, 62, 38, 35, 16,
         54, 24, 57, 35, 38, 62, 16, 35,  0, 24,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0, 24, 42, 47, 35, 42, 24, 16, 66, 24]])

In [ ]:
X = torch.zeros((len(encrypt_phrases), MAX_LEN), dtype=int)
for i in range(len(encrypt_phrases)):
    for j, w in enumerate(encrypt_phrases[i]):
        if j >= MAX_LEN:
            break
        X[i, j] = CHAR_TO_INDEX.get(w, CHAR_TO_INDEX['none'])

In [ ]:
X[0:3]

tensor([[15, 66, 34, 46, 35, 43, 54, 52, 60, 24, 13, 34, 60, 17, 34, 34, 30, 38,
          8, 24, 26, 31, 28, 46, 38, 54,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [40, 52, 28, 22, 22, 64, 17, 28, 24,  4, 52,  8, 24, 60, 17, 62, 52, 32,
         53, 64, 17, 62, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 6, 28, 63, 22,  8, 24, 66, 24,  1,  4, 42, 33, 22, 33, 24, 61,  0,  0,
         19,  0,  0, 65, 29, 30, 32, 42,  8, 22, 24,  0, 18, 66, 16, 41,  8, 42,
         31, 24, 56,  8, 41, 16, 42,  8,  0, 24,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0, 24, 28, 54,  8, 28, 24, 42, 35, 24]])

## Создание нейросети

In [ ]:
class Network(torch.nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.embed = torch.nn.Embedding(len(CHAR_TO_INDEX),68)
        self.rnn = torch.nn.RNN(68, 128, batch_first=True)
        self.linear = torch.nn.Linear(128, len(INDEX_TO_CHAR))
                
    def forward(self, sentences, state=None):
        embed = self.embed(sentences)
        o, s = self.rnn(embed)
        out = self.linear(o)
        return out

In [ ]:
model = Network()

In [ ]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=.05)

In [ ]:
model.train()
for epoch in range(1000):
    start = time.time()
    train_loss = 0.


    optimizer.zero_grad()
    answers = model.forward(X)
    loss = criterion(answers, y)
    train_loss += loss.item()

    loss.backward()
    optimizer.step()

    if (epoch+1) % 200 == 0:
        print("Epoch {}. Time: {:.3f}, Train loss: {:.3f}".format(epoch+1, time.time() - start, train_loss ))  

Epoch 200. Time: 0.781, Train loss: 1.734
Epoch 400. Time: 0.765, Train loss: 1.604
Epoch 600. Time: 0.783, Train loss: 1.579
Epoch 800. Time: 0.842, Train loss: 1.570
Epoch 1000. Time: 0.735, Train loss: 1.565


## данные для теста


In [ ]:
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ds/filatov.txt', sep='\n\r')
df_test.head(20)

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


Леонид Филатов
0                                 Про Федота-Стрельца
1                                   Сказка для театра
2                     (По мотивам русского фольклора)
3                                   Скоморох-потешник
4   Верьте аль не верьте, а жил на белом свете Фед...
5                                                Царь
6                            К нам на утренний рассол
7                              Прибыл аглицкий посол,
8                            А у нас в дому закуски –
9                               Полгорбушки да мосол.
10                         Снаряжайся, братец, в путь
11                          Да съестного нам добудь –
12                             Глухаря аль куропатку,
13                               Аль ишо кого-нибудь.
14                        Не смогешь – кого винить? –
15                             Я должон тебя казнить.
16                             Государственное дело –
17                             Ты улавливаешь нить?..
18                                              Федот
19                                Нешто я да не пойму

In [ ]:
phrases_test = df_test['Леонид Филатов'].tolist()
phrases_test[:3]

['Про Федота-Стрельца', 'Сказка для театра', '(По мотивам русского фольклора)']

In [ ]:
encrypt_phrases_test = []
#print('сдвиг: ', n)
for i in range(len(phrases_test)):
  str = phrases_test[i]
  #str_enc = encrypt(str, int(n))
  str_enc = encrypt(str, random.randint(1, len(small_symbols)-1))
  encrypt_phrases_test.append(str_enc)

print('оригинальный тестовый текст:  ', phrases_test[:3])
print('зашифрованный тестовый текст: ', encrypt_phrases_test[:3])

оригинальный тестовый текст:   ['Про Федота-Стрельца', 'Сказка для театра', '(По мотивам русского фольклора)']
зашифрованный тестовый текст:  ['Рсп Хёепуб-Тусёмэчб', 'Щтзптз луж ъмзъшз', '(Ая эягщтрэ бдввыяуя еяьмыьябр)']


In [ ]:
y_test = torch.zeros((len(phrases_test), MAX_LEN), dtype=int)
for i in range(len(phrases_test)):
    for j, w in enumerate(phrases_test[i]):
        if j >= MAX_LEN:
            break
        y_test[i, j] = CHAR_TO_INDEX.get(w, CHAR_TO_INDEX['none'])

In [ ]:
print(CHAR_TO_INDEX['П'],CHAR_TO_INDEX['р'],CHAR_TO_INDEX['о'], CHAR_TO_INDEX[' '], CHAR_TO_INDEX['Ф'])
y_test[0:3]

50 32 42 24 56


tensor([[50, 32, 42, 24, 56, 38, 47, 42, 63, 52,  0,  3, 63, 32, 38, 20, 43, 23,
         52,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 3, 41, 52, 66, 41, 52, 24, 47, 20, 17, 24, 63, 38, 52, 63, 32, 52,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 50, 42, 24, 60, 42, 63, 16, 53, 52, 60, 24, 32,  8, 48, 48, 41, 42,
         62, 42, 24, 28, 42, 20, 43, 41, 20, 42, 32, 52,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
X_test = torch.zeros((len(encrypt_phrases_test), MAX_LEN), dtype=int)
for i in range(len(encrypt_phrases_test)):
    for j, w in enumerate(encrypt_phrases_test[i]):
        if j >= MAX_LEN:
            break
        X_test[i, j] = CHAR_TO_INDEX.get(w, CHAR_TO_INDEX['none'])

In [ ]:
X_test[0:3]

tensor([[ 2, 48, 31, 24, 65, 22, 38, 31,  8, 34,  0, 27,  8, 48, 22, 60, 64,  1,
         34,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [14, 63, 66, 31, 63, 66, 24, 20,  8, 46, 24, 45, 60, 66, 45,  4, 66,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 51, 17, 24, 64, 17, 62, 29, 63, 32, 64, 24, 34, 47, 53, 53, 33, 17,
          8, 17, 24, 38, 17, 43, 60, 33, 43, 17, 34, 32,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
model.eval()
y_pred = model(X_test)
loss = criterion(y_pred, y_test)
test_loss = loss.item()
        
print("\n test_loss: {:.3f} ".format(loss))


 test_loss: 1.486 
